### ISSUE TITLE
log.chatLogType.chatAttachmentl.url is always empty on android

### ISSUE THREAD

**Issue by caseyryan** [KohlsAdrian/zendesk2#15]
After sending a file using _zendesk.sendFile(file.path); The file is uploaded and operator can see it but the returned log on android has a null link. This happens when we just send the image. If it's loaded from history, everything is fine
On iOS it works just fine

**Comment by caseyryan** [comment]
Sorry, I found out how it works. It just sends updates after each change for all message. Not very optimal solution as to me, but is working. So I just need to check if something in a message has changed before updating a state

**Comment by KohlsAdrian** [comment]
I think the same, but that's is how the SDK works, the only thing that need to change is how Flutter retrieve the SDK data, that I used Timer instead of invokeHandler, [THIS PR](https://github.com/KohlsAdrian/zendesk2/pull/13) optimize it, however on iOS is not working properly, we are still looking into what need to get it back working
