### ISSUE TITLE
[Feature] Answer SDK

### ISSUE THREAD

**Issue by kjawadDeveloper1** [KohlsAdrian/zendesk2#22]
When we can expect the support for the answer sdk

**Comment by KohlsAdrian** [comment]
At the moment I have no plans on adding Answer SDK soon, I was paid to develop this plugin and I was focused on developing it

so as soon as I have free time to create new things for this plugin I should add this feature

**Comment by KohlsAdrian** [comment]
But you are free to contribute to this plugin, feel free to create a fork and request a PR so I can review it and merge it if it is all ok

**Comment by kjawadDeveloper1** [comment]
Sure i will try that

**Comment by KohlsAdrian** [comment]
Answer BOT code is ready for testing on iOS in the current PR state

However the company I am working to have no Answer BOT feature bought.
If someone can share privately Zendesk keys for me to finish testings I can continue the development
Otherwise Answer SDK development is frozen until I have access to Answer SDK product.

Waiting for contribution.

**Comment by KohlsAdrian** [comment]
Hi @ariefwijaya if you have AnswerSDK product in your Zendesk account and want to share it, please reach me out on discord

647#3772 

so we can discuss about it on private

**Comment by KohlsAdrian** [comment]
As there is no other people that could share the keys with me and I want to speed up the process I created a trial account on Zendesk for 14 days and enabled Answer BOT, release will be made soon

**Comment by KohlsAdrian** [comment]
Answer SDK is progressing, iOS almost finished, afterwards will be Android
